### ISSUE TITLE
Reconnect algorithm

### ISSUE THREAD

**Issue by chelsEg** [lizhichao/one-ck#5]
Hello!

I have some case when I got exception **Broken pipe**.

I use this library in demonic process (background task, runtime worker and etc).

After connection timed out I got error:

`
ErrorException(code: 0): fwrite(): send of 8192 bytes failed with errno=32 Broken pipe at /code/vendor/lizhichao/one-ck/src/Write.php:82
`

Maybe need algorithm of reconnect broken connection.

What do you mint about that?

**Comment by lizhichao** [comment]
Same as other database connectors ，in demonic process or background task, If you find a disconnection, you need to reconnect  In your own program。

**Comment by lizhichao** [comment]
like this https://github.com/lizhichao/one/blob/master/src/Database/ClickHouse/Connect.php#L113-L135

**Comment by chelsEg** [comment]
> Same as other database connectors ，in demonic process or background task, If you find a disconnection, you need to reconnect In your own program。

Oh ... in my case it will be difficult.
Because I use the framework (Laravel) in my project, and your library is the connector to ClickHouse.

I'm agree about reconnection logic, but this logic need realise in connector.

**Comment by lizhichao** [comment]
> > Same as other database connectors ，in demonic process or background task, If you find a disconnection, you need to reconnect In your own program。
> 
> Oh ... in my case it will be difficult.
> Because I use the framework (Laravel) in my project, and your library is the connector to ClickHouse.
> 
> I'm agree about reconnection logic, but this logic need realise in connector.

On one-ck, encapsulate it again

```php
class autoClient
{
    private $conn;

    private $params;

    public function __construct(...$params)
    {
        $this->params = $params;
        $this->getConn();
    }

    private function getConn()
    {
        $this->conn = new \OneCk\Client(...$this->params);
    }

    public function query($sql)
    {
        $i = 0;
        do {
            try {
                return $this->conn->query($sql);
            } catch (\Exception $e) {
                echo $e->getMessage();
                //re connect
                $this->getConn();;
                $i++;
            }
        } while ($i < 2);
    }
}
```

**Comment by chelsEg** [comment]
> > > Same as other database connectors ，in demonic process or background task, If you find a disconnection, you need to reconnect In your own program。
> > 
> > 
> > Oh ... in my case it will be difficult.
> > Because I use the framework (Laravel) in my project, and your library is the connector to ClickHouse.
> > I'm agree about reconnection logic, but this logic need realise in connector.
> 
> On one-ck, encapsulate it again
> 
> ```
> class autoClient
> {
>     private $conn;
> 
>     private $params;
> 
>     public function __construct(...$params)
>     {
>         $this->params = $params;
>         $this->getConn();
>     }
> 
>     private function getConn()
>     {
>         $this->conn = new \OneCk\Client(...$this->params);
>     }
> 
>     public function query($sql)
>     {
>         $i = 0;
>         do {
>             try {
>                 return $this->conn->query($sql);
>             } catch (\Exception $e) {
>                 echo $e->getMessage();
>                 //re connect
>                 $this->getConn();;
>                 $i++;
>             }
>         } while ($i < 2);
>     }
> }
> ```

Okay, thanks!

I try use it.
