### ISSUE TITLE
Async queries

### ISSUE THREAD

**Issue by bun4uk** [lizhichao/one-ck#7]
Is it possible to execute async queries using this lib?

**Comment by lizhichao** [comment]
> Is it possible to execute async queries using this lib?

like this ?
```
$ck->query($sql,function ($response){
    
});
```
not support

**Comment by bun4uk** [comment]
What about parallel execution of multiple queries?
Something like this:
```
$ck->($sql1);
$ck->($sql2);
$ck->($sql3);
$ck->executeAsync();
```

**Comment by lizhichao** [comment]
> What about parallel execution of multiple queries?
> Something like this:
> 
> ```
> $ck->($sql1);
> $ck->($sql2);
> $ck->($sql3);
> $ck->executeAsync();
> ```

Currently still not supported
