### ISSUE TITLE
Bug with hash function sipHash64

### ISSUE THREAD

**Issue by chelsEg** [lizhichao/one-ck#8]
Hello.

I have bug with function [sipHash64](https://clickhouse.tech/docs/en/sql-reference/functions/hash-functions/#hash_functions-siphash64).

```
$sql = "SELECT sipHash64(toString('1ace54')) AS result";

$result = $client->query($sql);

var_dump($result);
```

You see this:

```
Array
(
    [0] => Array
        (
            [result] => -8921094594927452419
        )
)
```

Then run query in one of DB viewer:

<img width="367" alt="Снимок экрана 2021-07-21 в 13 25 41" src="https://user-images.githubusercontent.com/16079950/126474341-d4a3e6f3-9205-4a75-b289-e6ecadeb0c44.png">

This bug happens because there are numbers in the input string.

**ClickHouse version:** 20.8.18.32

**Comment by lizhichao** [comment]
php does not support uint64.
Now uint64  changed to a string in `0.2.7`

**Comment by chelsEg** [comment]
Thanks for fix.
