### ISSUE TITLE
Close connection

### ISSUE THREAD

**Issue by chelsEg** [lizhichao/one-ck#9]
Hello.

In my project I use this library for high load (~ 800-1000 rps) work with ClickHouse.

Sometimes open connections in ClickHouse increase, which leads to errors:

`stream_socket_client(): unable to connect to tcp://clickhouse.services:9000 (Connection timed out)`.

This happened because connections don't closed after using, they closed by ClickHouse after tcp_keep_alive_timeout.

I'm propose forcibly close connection after use.

Something like this:

```
class Client
{
...
public function __destruct()
{
   fclose($this->conn);
}
...
}
```

What you mind about this?

**Comment by lizhichao** [comment]
good idea 👍

**Comment by chelsEg** [comment]
> good idea 👍

When do you release this MR?
